language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"

install:
  - git clone -b fix-coverage https://github.com/dreispt/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
